version: 2

project_name: wirego

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: wirego
    ldflags:
      - -s -w
      - -X github.com/HappyRish01/wirego/cmd.Version={{.Version}}
      - -X github.com/HappyRish01/wirego/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/HappyRish01/wirego/cmd.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
